#pragma once

enum Error : int {
	SUCCESS = 0,
	PARSE_ERROR = 10,
	CLIENT_ERROR = 20,
	PROTOCOL_ERROR = 30,
	MESSAGE_ERROR = 31,
	NETWORK_ERROR = 40,
	TIMEOUT_ERROR = 50,
	GENERAL_ERROR = 60,
	SERVER_ERROR = 80
};